# -*- coding: utf-8 -*-
"""Untitled94.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NyvQeNH_LftImOz6NKM26GEN84ze132K
"""

import numpy as np

# -----------------------------
# 1. Training data
# -----------------------------
X_raw = np.array([
    [4, 6, 8],
    [5, 7, 9],
    [6, 8, 10],
    [8, 10, 12]
], dtype=float)

y_raw = np.array([
    [100],
    [110],
    [120],
    [140]
], dtype=float)

# Scale the data to make training easier
X = X_raw / 10
y = y_raw / 100

# -----------------------------
# 2. Create one neuron
# y = x1*w1 + x2*w2 + x3*w3 + b
# -----------------------------
np.random.seed(1)

w = np.random.randn(3, 1) * 0.01
b = 0.0

learning_rate = 0.5
epochs = 1500

# -----------------------------
# 3. Train the neuron
# -----------------------------
for epoch in range(1, epochs + 1):

    # Forward pass
    y_pred = np.dot(X, w) + b

    # Error
    error = y_pred - y

    # Loss
    loss = np.mean(error ** 2)

    # Gradients
    dw = np.dot(X.T, error) / len(X)
    db = np.mean(error)

    # Update weights and bias
    w = w - learning_rate * dw
    b = b - learning_rate * db

    # Print progress
    if epoch % 300 == 0:
        print(f"Epoch {epoch}, Loss = {loss:.10f}")

# -----------------------------
# 4. Prediction function
# -----------------------------
def predict(a, b_, c):
    x = np.array([[a, b_, c]], dtype=float)

    # scale input
    x = x / 10

    # neuron output
    result = np.dot(x, w) + b

    # return to original scale
    result = result * 100

    return result[0][0]

# -----------------------------
# 5. Test the trained neuron
# -----------------------------
print("\nTraining examples:")
for i in range(len(X_raw)):
    a, b_, c = X_raw[i]
    print(f"{int(a)} ⊙ {int(b_)} ⊙ {int(c)} = {predict(a, b_, c):.0f}")

print("\nNew questions:")
print(f"14 ⊙ 16 ⊙ 18 = {predict(14, 16, 18):.0f}")
print(f"22 ⊙ 24 ⊙ 26 = {predict(22, 24, 26):.0f}")